### PR TITLE
Minimal cargo-c support

### LINKED ISSUE #437: Use cargo-c
[cargo-c](https://github.com/lu-zero/cargo-c) exists exactly to ease the build of Rust programs into C libraries, it's an easier and less error-prone approach

### PR DESCRIPTION
**Pull request by lu-zero**
Fixes #437

### CODE REVIEW

**Comment by penberg** [comment]
Looks like something broke with the C library build:

```
LIBS="../.././target/debug/liblimbo_sqlite3.a" make -C sqlite3/tests test
make[1]: Entering directory '/home/runner/work/limbo/limbo/sqlite3/tests'
  CC       main.o
  CC       test-aux.o
  CC       test-close.o
  CC       test-open.o
  CC       test-prepare.o
  LINK     sqlite3-tests
/usr/bin/ld: cannot find ../.././target/debug/liblimbo_sqlite3.a: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:36: sqlite3-tests] Error 1
make[1]: Leaving directory '/home/runner/work/limbo/limbo/sqlite3/tests'
make: *** [Makefile:63: test-sqlite3] Error 2
```

**Comment by lu-zero** [comment]
I didn't port the tests yet, cargo-c has a mean to run C-tests on its own or if you want to preserve the Makefile you may use the uninstalled pkg-config it produces.

**Comment by penberg** [comment]
@lu-zero I think we need to preserve the Makefile because you want to be able to run the same tests with both Limbo _and_ SQLite?

**Comment by lu-zero** [comment]
Sure, I can expand it to use `pkg-config` if you deem it useful.

**Pull request merged**
